services:
  SendMail:
    image: mathieumafille/sendmail:latest
    ports:
      - 5000:5000
    restart: always
    environment:
      - SERVER="mail.example.com"
      - PORT=587
      - SENDER="email@example.com"
      - PASSWORD="ExamPle"
